package arduinojava;


/**
 *
 * @author Raed
 */
public class Indicator extends javax.swing.JFrame {

    /**
     * Creates new form Indicator
     */
    public Indicator() {
        initComponents();

        Thread t = new Thread() {
            ArduinoJava main = new ArduinoJava();

            public void run() {
                main.initialize();

                while (true) {
                    try {
                        if (main != null) {
                            if (main.GetS() != null) {
                                // System.out.println("S :" + main.GetS());
                                int[] cord = new int[3];
                                cord[0] = main.GetS()[0];
                              //  cord[1] = main.GetS()[1];
                             //   cord[2] = main.GetS()[2];
                                if (cord[0] == 0) {
                                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduinojava/market0.png"))); // NOI18N
                                } else if (cord[0] == 1) {
                                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduinojava/market1.png"))); // NOI18N
                                } else if (cord[0] == 2) {
                                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduinojava/market2.png"))); // NOI18N
                                } else if (cord[0] == 3) {
                                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduinojava/market3.png"))); // NOI18N
                                } else {
                                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduinojava/loading.png"))); // NOI18N
                                }

                                //  jLabel1.setText("x :" + cord[0] + " y: " + cord[1] + " z " + cord[2]);
                                this.main.ReSetS();
                            }
                        } else {
                            System.out.println("WHy is this null?");
                        }
                        System.out.println("RESTING");
                        Thread.sleep(1000); // keep this mess open for 1000 sec 
                    } catch (InterruptedException ie) {
                    }
                }

            }
        };

        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduinojava/loading.png"))); // NOI18N
        jLabel1.setName("mob"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("mob");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {

                new Indicator().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
